# Generated by Django 5.2.17 on 2026-08-16 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_id', models.CharField(max_length=64)),
                ('plan_id', models.CharField(blank=True, max_length=64)),
                ('service_name_snapshot', models.CharField(max_length=200)),
                ('plan_name_snapshot', models.CharField(blank=True, max_length=200)),
                ('price_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('scope', models.TextField()),
                ('status', models.CharField(choices=[('onboarding', 'Onboarding'), ('research', 'Research'), ('strategy', 'Strategy'), ('draft', 'Draft'), ('review', 'Review'), ('revision', 'Revision'), ('approved', 'Approved'), ('delivered', 'Delivered'), ('archived', 'Archived')], db_index=True, default='onboarding', max_length=30)),
                ('started_at', models.DateField(blank=True, null=True)),
                ('due_at', models.DateField(blank=True, null=True)),
                ('delivered_at', models.DateField(blank=True, null=True)),
                ('revision_count', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='clients.client')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('todo', 'To do'), ('in_progress', 'In progress'), ('blocked', 'Blocked'), ('done', 'Done')], db_index=True, default='todo', max_length=20)),
                ('due_at', models.DateField(blank=True, null=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project')),
            ],
            options={
                'ordering': ['position', 'created_at'],
            },
        ),
    ]
