# Generated by Django 5.2.17 on 2026-08-17 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_source_lead'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('created', 'Project created'), ('status_change', 'Status change'), ('due_date_change', 'Due date change'), ('note', 'Internal note'), ('task_created', 'Task created'), ('task_status_change', 'Task status change'), ('delivered', 'Project delivered'), ('reopened', 'Project reopened')], max_length=30)),
                ('description', models.TextField()),
                ('occurred_at', models.DateTimeField()),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_activities', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='projects.project')),
            ],
            options={
                'ordering': ['-occurred_at', '-created_at'],
            },
        ),
    ]
