# Generated by Django 5.2.17 on 2026-08-16 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('email', 'Email'), ('call', 'Call'), ('follow_up', 'Follow-up'), ('proposal', 'Proposal'), ('status_change', 'Status change'), ('note', 'Internal note')], default='note', max_length=30)),
                ('note', models.TextField()),
                ('occurred_at', models.DateTimeField()),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='leads.lead')),
            ],
            options={
                'ordering': ['-occurred_at', '-created_at'],
            },
        ),
    ]
