# Generated by Django 5.2.17 on 2026-08-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('contact', 'Contact'), ('project', 'Project'), ('partnership', 'Partnership')], db_index=True, default='contact', max_length=30)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('website', models.URLField(blank=True)),
                ('service_interest_id', models.CharField(blank=True, max_length=64)),
                ('plan_interest_id', models.CharField(blank=True, max_length=64)),
                ('message', models.TextField()),
                ('utm_source', models.CharField(blank=True, max_length=120)),
                ('utm_medium', models.CharField(blank=True, max_length=120)),
                ('utm_campaign', models.CharField(blank=True, max_length=120)),
                ('referrer', models.URLField(blank=True)),
                ('landing_page', models.CharField(blank=True, max_length=500)),
                ('handled', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
