# Generated by Django 5.2.17 on 2026-08-16 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0002_leadactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], db_index=True, default='active', max_length=20)),
                ('since', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='client', to='leads.company')),
            ],
            options={
                'ordering': ['company__name'],
            },
        ),
    ]
