# Generated by Django 5.2.17 on 2026-08-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.CharField(choices=[('page_view', 'Page view'), ('service_view', 'Service view'), ('pricing_view', 'Pricing view'), ('case_study_view', 'Case study view'), ('cta_clicked', 'CTA clicked'), ('contact_started', 'Contact started'), ('contact_submitted', 'Contact submitted'), ('project_form_started', 'Project form started'), ('project_form_submitted', 'Project form submitted'), ('lead_qualified', 'Lead qualified'), ('discovery_scheduled', 'Discovery scheduled'), ('proposal_created', 'Proposal created'), ('project_won', 'Project won'), ('project_delivered', 'Project delivered'), ('retainer_offered', 'Retainer offered'), ('retainer_won', 'Retainer won')], db_index=True, max_length=50)),
                ('path', models.CharField(blank=True, max_length=500)),
                ('referrer', models.CharField(blank=True, max_length=500)),
                ('lead_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('project_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('utm_source', models.CharField(blank=True, max_length=120)),
                ('utm_medium', models.CharField(blank=True, max_length=120)),
                ('utm_campaign', models.CharField(blank=True, max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event', 'created_at'], name='analytics_a_event_304b34_idx')],
            },
        ),
    ]
