# Generated by Django 5.2.17 on 2026-08-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('demonstration', 'Demonstration'), ('client', 'Client work')], default='demonstration', max_length=30)),
                ('service_id', models.CharField(max_length=64)),
                ('summary', models.TextField()),
                ('situation', models.TextField(blank=True)),
                ('objective', models.TextField(blank=True)),
                ('baseline', models.TextField(blank=True)),
                ('diagnosis', models.TextField(blank=True)),
                ('strategy', models.TextField(blank=True)),
                ('improved_version', models.TextField(blank=True)),
                ('evaluation', models.TextField(blank=True)),
                ('published', models.BooleanField(db_index=True, default=False)),
                ('featured', models.BooleanField(db_index=True, default=False)),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['position', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('role', models.CharField(blank=True, max_length=120)),
                ('quote', models.TextField()),
                ('approved', models.BooleanField(db_index=True, default=False)),
                ('featured', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
